export default {
  SYNC_USER: 'SYNC_USER', //存储用户信息
  SYNC_BASE_API: 'SYNC_BASE_API', //修改服务端接口基础路径
  SYNC_TOKEN: 'SYNC_TOKEN', //更新token
  INIT_LOCAL_DADA: 'INIT_LOCAL_DADA', //初始化本地数据
  STASH_TYPES: 'STASH_TYPES', //暂存
  LOCATE: 'LOCATE',
  SAVE_PART_TYPE: 'SAVE_PART_TYPE',
  SAVE_LAYER_USAGE: 'SAVE_LAYER_USAGE', //暂存图层用途
  EDIT_ADDRESS: 'EDIT_ADDRESS',
  SAVE_LAYER_SWITCH: 'SAVE_LAYER_SWITCH', //保存部件图层开关
  SYNC_DIC_DATA: 'SYNC_DIC_DATA', //字典表数据和区划筛选数据
  UPDATE_ONLINE_STATUS: 'UPDATE_ONLINE_STATUS', //更新用户在线状态
};
